"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import psycopg2
import dj_database_url
import django_heroku

#DATABASE_URL = os.environ['DATABASE_URL']

#conn = psycopg2.connect(DATABASE_URL, sslmode='require')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o_6dyu1#(l*qg!(^7r-s18o8r&!rf5jw5y9vtw4^u7fph*x6_4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['dona-digital-marketing.herokuapp.com','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'blog',
    'users',
    'crispy_forms',
    'ckeditor',
    'ckeditor_uploader',
    'storages',



    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

SITE_ID = 1

CKEDITOR_UPLOAD_PATH = 'ckupload/'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates'), os.path.join(BASE_DIR,'templates','allauth')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
             
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [

    'django.contrib.auth.backends.ModelBackend',

    'allauth.account.auth_backends.AuthenticationBackend',

]

WSGI_APPLICATION = 'website.wsgi.application'

#DATABASES=['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)
# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'database_name',
        'USER': 'database_username',
        'PASSWORD': 'database_password',
        'HOST': 'database_endpoint',
        'PORT': 'database_port',
    }

}
'''
#import psycopg2

#conn = psycopg2.connect(
#     host ='ec2-54-205-248-255.compute-1.amazonaws.com',
#     database ='de2a6c1jbgd47q',
#     user ='sendcrnqcjoboz',
#     password ='b74e7350e0cd0e99deff80bbad27ea7e4cbb470c1c64f5317b200cda0bf6e17a',
#     port ='5432'
#    )
#print("connected to postgreSQL DB")
#conn.close()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dona_marketing',
        'USER': 'postgres',
        'HOST': 'localhost',
        'PASSWORD': 'peter123',
        'PORT': '5432'

    }
}
#S3 BUCKETS CONFIG
AWS_ACCESS_KEY_ID ='AKIAXRD5BYG7BRHDXP6I'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'dona-marketing-files'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

#DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)

db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#crispy form

CRISPY_TEMPLATE_PACK = 'bootstrap4'

#LOGIN_REDIRECT_URL = 'post-list'
#LOGOUT_REDIRECT_URL = 'post-list'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'update' : ['image', 'update', 'table', 'HorizontalRule', 'Smiley', 'SpecialChar']
    },
}

CKEDITOR_UPLOAD_PATH = 'ckeditor/'

django_heroku.settings(locals())